### ISSUE TITLE
Project not configured !!

### ISSUE THREAD

**Issue by divyankkarolia97** [mrf345/online-wallpapers#1]
Heads up, I tried running the project on my local machine, firstly the new version of react-native doesn't support react-native start && react-native run.

when i tried
**react-native run-android** with v55.4

It thew an error that the project was not configured correctly.

P.S: I am fairly new to react-native and don't know the ins and outs of it.

**Comment by mrf345** [comment]
@divyankkarolia97  Thanks for the heads up. 
I did a typo  in package.json, i left a space in the project name, 
so that's fixed. And forget to mention[ a known issue here](https://github.com/mrf345/online-wallpapers#known-issues).
